# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42a715c6630e9de7620a25d8f7cbf8e2405ba94aab1b48b0062acbe37c9e5ab1dc08fa4e9d31877ca9f8065c31051dd1fb38594c6684b9e6c2d2aa9a035441e4

test:
  secret_key_base: bab465acbefe65697052f9b70af9a49e0461ddf046184dfcae4f4e56b6ae28696417c3b09fb43c9b2a1f331f214ed599449a7260db97e6e90f99355fdecc0190

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
